on: [push]

jobs:
  build_and_verify:
    name: "Build code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-unknown-none-softfloat
          default: true
          components: rust-src
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: "Installing binutils aarch64"
        run: sudo apt update && sudo apt install binutils-aarch64-linux-gnu
      - name: "Building aarch64-linux"
        run: env DEBUG=1 TARGET=aarch64 PROTO=linux OBJCOPY=/usr/aarch64-linux-gnu/bin/objcopy make build
      - uses: actions/upload-artifact@v3
        with:
          name: "kernel-elf"
          path: "kernel"
      - uses: actions/upload-artifact@v3
        with:
          name: "kernel-bin"
          path: "kernel.bin"